receivers:
  hostmetrics:
    collection_interval: 10s
    
exporters:
  prometheus:
    endpoint: "0.0.0.0:9464"

service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      exporters: [prometheus]
