version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=true
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - elk-net

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:8.14.3
  #   environment:
  #     - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  #     - XPACK_SECURITY_ENABLED=false
  #   ports:
  #     - "5601:5601"
  #   depends_on:
  #     - elasticsearch
  #   networks:
  #     - elk-net

  logstash:
    image: docker.elastic.co/logstash/logstash:8.14.3
    environment:
      - xpack.monitoring.enabled=false
      - LS_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/templates:/usr/share/logstash/templates
      - ./logs:/var/log/ingest
    depends_on:
      - elasticsearch
    networks:
      - elk-net
    ports:
      - "5044:5044"   # reserved if you later add beats
      - "9600:9600"   # logstash monitoring API

volumes:
  esdata:

networks:
  elk-net:
    driver: bridge
